apiVersion: v1
data:
  {{ if .Values.oidc.caPEM }}
  oidc.ca-pem: {{ .Values.oidc.caPEM | default "" | b64enc }}
  {{ end }}
  oidc.issuer-url: {{ .Values.oidc.issuerUrl | b64enc }}
  oidc.username-claim: {{ .Values.oidc.usernameClaim | b64enc }}
  oidc.client-id: {{ .Values.oidc.clientId | b64enc }}
  oidc.username-prefix: {{ .Values.oidc.usernamePrefix | default "" | b64enc }}
  oidc.groups-claim: {{ .Values.oidc.groupsClaim | default "" | b64enc }}
  oidc.groups-prefix: {{ .Values.oidc.groupsPrefix | default "" | b64enc }}
  oidc.signing-algs: {{ join "," .Values.oidc.signingAlgs | default "" | b64enc }}
  oidc.required-claims: {{ include "requiredClaims" . | b64enc }}
  api-audiences: {{ join "," .Values.oidc.apiAudiences | default "" | b64enc }}
kind: Secret
metadata:
  name: {{ include "kube-oidc-proxy.fullname" . }}-config
  labels:
{{ include "kube-oidc-proxy.labels" . | indent 4 }}
type: Opaque