---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedAddon
metadata:
  name: kube-oidc-proxy-kommander
  namespace: kommander-system
spec:
  placement:
    clusterSelector:
      matchLabels: {}
  template:
    metadata:
      namespace: kommander-system
      labels:
        kubeaddons.mesosphere.io/name: kube-oidc-proxy-kommander
      annotations:
        appversion.kubeaddons.mesosphere.io/kube-oidc-proxy: "v0.1.1"
        values.chart.helm.kubeaddons.mesosphere.io/kube-oidc-proxy: "https://raw.githubusercontent.com/mesosphere/charts/fb01c5b81bb77e78d3a9ff5f5d8ec4b2703c5fb4/staging/kube-oidc-proxy/values.yaml"
    spec:
      namespace: kommander-system
      chartReference:
        chart: kube-oidc-proxy
        repo: https://mesosphere.github.io/charts/staging
        values: |
          ---
          image:
            repository: quay.io/jetstack/kube-oidc-proxy
            tag: v0.1.1
            pullPolicy: IfNotPresent

          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
              ingress.kubernetes.io/protocol: https
              traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
            path: /kommander/api-server
            hosts:
              - ""

          # Created by init-container
          # NOTE: init-container does not run here.
          tls:
            secretName: kube-oidc-proxy-kubeaddons-server-tls

          oidc:
            clientId: kube-apiserver
            # updated by initcontainer when working with a remote dex
            issuerUrl: https://placeholder/dex
            usernameClaim: email
            groupsPrefix: "oidc:"
            caPEM: "placeholder"

          initContainers: null
        version: 0.1.4
      cloudProvider:
      - enabled: true
        name: aws
      - enabled: true
        name: docker
      - enabled: true
        name: none
      kubernetes:
        minSupportedVersion: v1.15.0
      requires:
      - matchLabels:
          kubeaddons.mesosphere.io/provides: ingresscontroller
