apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
    control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-webhook
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
