nameOverride: "kommander-cluster-lifecycle"

fullnameOverride: "kcl"

## Labels to apply to all resources
##
commonLabels: {}

controller:
  containers:
    manager:
      replicas: 1
      image:
        repository: mesosphere/kommander-cluster-lifecycle-controller-manager
        tag:
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 128Mi
    proxy:
      image:
        repository: gcr.io/kubebuilder/kube-rbac-proxy
        tag: v0.4.0
        pullPolicy: IfNotPresent
      resources: {}
  securityContext:
    runAsUser: 65534
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

webhook:
  image:
    repository: mesosphere/kommander-cluster-lifecycle-webhook
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
  securityContext:
    runAsUser: 65534
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

terraformBackend:
  replicas: 1
  image:
    repository: jimmidyson/tf-kubernetes-configmap-backend
    tag: v0.1.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
  securityContext:
    runAsUser: 65534
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

konvoy:
  imageRepository: mesosphere/konvoy

certificates:
  issuer:
    name:
    kind: Issuer
    selfSigned: false

utilityApiserver:
  allowUnofficialReleases: false
  image:
    repository: mesosphere/kommander-cluster-lifecycle-utility-apiserver
    tag: dev
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  securityContext:
    runAsUser: 65534
  service:
    annotations: {}
    type: ClusterIP
    port: 443
