{{- if .Values.federate.systemNamespace.enable -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.federate.systemNamespace.name }}
  labels:
    app: {{ template "kommander.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedNamespace
metadata:
  name: {{ .Values.federate.systemNamespace.name }}
  namespace: {{ .Values.federate.systemNamespace.name }}
spec:
  placement:
    clusterSelector:
      matchLabels: {}
  template:
    spec: {}
{{- end -}}
