{{- if (eq "konvoy" .Values.mode) }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ template "kommander.fullname" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ template "kommander.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    kommanderType: clusterToken
---
apiVersion: "stable.mesosphere.com/v1"
kind: ObservableCluster
metadata:
  name: konvoy
  namespace: {{ .Release.Namespace }}
spec:
  displayName: {{ .Values.displayName }}
  authenticationSecretName: {{ template "kommander.fullname" . }}-token
  apiServer: https://kubernetes.default
{{ end }}
